# simple docker-compose wih db service which is postgresql 15

version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
