import { ThemeProvider } from "@/components/providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard - Hiep's Homelab",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  favicon: "https://static.hieptuanle.com/homelab/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter.className
          )}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="relative flex min-h-screen flex-col">
              {/* <SiteHeader /> */}
              <div className="flex-1">{children}</div>
              {/* <SiteFooter /> */}
            </div>
          </ThemeProvider>
          <div className="dark"></div>
        </body>
      </html>
    </>
  );
}
